# Generated by Django 5.1.2 on 2024-10-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
    ]
