# Generated by Django 5.1.2 on 2024-10-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AcccountEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('credit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='budget.account')),
                ('debit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='budget.account')),
            ],
        ),
    ]
