# Generated by Django 5.1.2 on 2024-12-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_budgetbracket_category_category2budgetbracket_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcccountEntry',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
