# Generated by Django 5.1.2 on 2025-01-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcccountEntry',
        ),
    ]
