# Generated by Django 5.1.2 on 2025-01-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_acccountentry'),
        ('budget', '0004_delete_acccountentry_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcccountEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_name_category', to='budget.category')),
                ('credit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='account.account')),
                ('debit_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='account.account')),
            ],
        ),
    ]
