# Generated by Django 5.1.2 on 2025-01-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_delete_acccountentry_delete_account'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acccountentry',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_name_category', to='budget.category'),
        ),
    ]
