# Generated by Django 5.1.2 on 2025-01-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_acccountentry'),
        ('expenses', '0002_alter_acccountentry_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acccountentry',
            name='credit_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='acccountentry',
            name='debit_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_account', to='account.account'),
        ),
    ]
