# Generated by Django 5.1.2 on 2025-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_acccountentry_credit_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acccountentry',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
